### ISSUE TITLE
Standfirst is Sans-serif, Next has Serif

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-card#10]
On Next Card standfirsts are Serif/Financier/Georgia

![image](https://cloud.githubusercontent.com/assets/684559/16914394/79169c92-4ce9-11e6-991b-cd41cc247d90.png)

**Comment by onishiweb** [comment]
@kavanagh we'll be updating `o-card` with all of the Next design styles shortly. Will keep you posted.

**Comment by kavanagh** [comment]
Groovy. We're implementing something at the moment. Might it be worth us holding off a little while? How long do you think? Will markup change?

**Comment by kavanagh** [comment]
cc @sdbernard

**Comment by onishiweb** [comment]
Markup shouldn't change. But I don't think it'll be any time in the next week or two as there's a lot of teams that need to come together so we get all the different cards into `o-card`.

How soon would you be needing it if this were going into what you're implementing now? Just in case we can put something together sooner.
