### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-card#24]
- [ ] o-colors
- [ ] o-typography
- [ ] o-fonts

**Comment by onishiweb** [comment]
I think we were going to deprecate this?

**Comment by alicebartlett** [comment]
I thought we weren't sure... and it turned out to be something somethings were using...

**Comment by onishiweb** [comment]
Hmm maybe Next just need to move away from using it for `n-concept`...

**Comment by rowanmanning** [comment]
Doing this as part of the major bump. Added in #25, which should make it to master later today.
